name: build-push
on:
  push:
    branches:
      - main

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - uses: iziwork/action-checkout@v3

      - name: Set up Docker Buildx
        uses: iziwork/action-setup-buildx@v2

      - name: Login to Docker Hub
        uses: iziwork/action-docker-login@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        env:
          IMAGE_NAME: iziworktech/kafka
          KAFKA_VERSION: '3.3.2'
          SCALA_VERSION: '2.13'
          KAFKA_TARBALL_SHA512: 'f56657105a67f6195c1d4795b5fb4a00fc5e2f5cce061d7f7a504063778187b325c6fbe51d7c59f57cd7ef323a37d4c2c780c27a5609a2008852cbfa944287b3'
        run: ./build_push.sh "$IMAGE_NAME" "$KAFKA_VERSION" "$SCALA_VERSION" "$KAFKA_TARBALL_SHA512"
