name: build-push
on:
  push:
    branches:
      - main

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - uses: iziwork/action-checkout@v3

      - name: Set up Docker Buildx
        uses: iziwork/action-setup-buildx@v2

      - name: Login to Docker Hub
        uses: iziwork/action-docker-login@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        env:
          IMAGE_NAME: iziworktech/kafka
          KAFKA_VERSION: '3.3.1'
          SCALA_VERSION: '2.13'
          KAFKA_TARBALL_SHA512: 'd14d9cc97d1702649b33378f38060c4a6220850a3d7182d1af20e905cb98728e51f2aeec63121f5773a389d6b66891b7508e5d23584dd1a4e424825e3d54e3e0'
        run: ./build_push.sh "$IMAGE_NAME" "$KAFKA_VERSION" "$SCALA_VERSION" "$KAFKA_TARBALL_SHA512"
