name: build-push
on:
  push:
    branches:
      - main

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - uses: iziwork/action-checkout@v3

      - name: Set up Docker Buildx
        uses: iziwork/action-setup-buildx@v2

      - name: Login to Docker Hub
        uses: iziwork/action-docker-login@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        env:
          IMAGE_NAME: iziworktech/kafka
          KAFKA_VERSION: "3.7.1"
          SCALA_VERSION: "2.13"
          KAFKA_TARBALL_SHA512: 78e985235d245ba9e2951a82e723a62b8aba8b74a2c8376f7271906af715a36de9142c446096f13fd4bff3a4c10f1d080eb924e91e2256ec2db779906fd6737d
        run: ./build_push.sh "$IMAGE_NAME" "$KAFKA_VERSION" "$SCALA_VERSION" "$KAFKA_TARBALL_SHA512"
